### ISSUE TITLE
HOXD13 location fix in hg19

### ISSUE THREAD

**Issue by Tianyibian** [hdashnow/STRchive#5]
Hi, I believe there is a very tiny mistake in the HOXD13 locations, likly the last digit was missing.
I believe for hg19 the correct location is  chr2	176957786	176957831   
Whereas currently the coordinate in the hg19.STRchive-disease-loci.TRGT.bed is  chr2	176957786	17695783
which miss the last digit 1
the issue does not apply to the hg38 file I believe.
Thank you so much if you can fix this problem.

**Comment by hdashnow** [comment]
Thanks for catching this @Tianyibian! I've pushed the fix.
